CREATE DATABASE COURRIER
USE COURRIER

CREATE TABLE ADMINISTRADOR(
ID INT IDENTITY PRIMARY KEY,
USERNAME VARCHAR(25) NOT NULL,
CLAVE VARCHAR(30) NOT NULL
)

INSERT INTO ADMINISTRADOR VALUES ('joanmf','administrador')
INSERT INTO ADMINISTRADOR VALUES ('andresra','administrador')
INSERT INTO ADMINISTRADOR VALUES ('joeljb','admnistrador')
INSERT INTO ADMINISTRADOR VALUES ('pedro','administrador')

CREATE TABLE EMPLEADOS(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
CODIGO INT NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
CLAVE VARCHAR(30) NOT NULL,
NOMBRE VARCHAR (30) NOT NULL,
APELLIDO VARCHAR (30) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
DEPARTAMENTO VARCHAR (30) NOT NULL,
CARGO VARCHAR (30) NOT NULL,
FECHA_INGRESO VARCHAR(20) NOT NULL,
SALARIO decimal(18,2) NOT NULL,
ESTATUS VARCHAR (15) NOT NULL
)

CREATE TABLE SALIDAEMPLEADOS(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMPLEADO INT FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS (ID),
MOTIVO VARCHAR(30) NOT NULL,
TIPO_SALIDA VARCHAR(30)NOT NULL,
FECHA_SALIDA VARCHAR(20) NOT NULL
)

CREATE TABLE LICENCIAS(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMPLEADO INT FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS (ID),
DESDE VARCHAR(30) NOT NULL,
HASTA VARCHAR(30) NOT NULL,
COMENTARIO VARCHAR(100) NOT NULL,
)

CREATE TABLE VACACIONES(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMPLEADO INT FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS (ID),
DESDE VARCHAR(30) NOT NULL,
HASTA VARCHAR(30) NOT NULL,
AÑO_CORRESPONDIENTE VARCHAR (30) NOT NULL,
COMENTARIO VARCHAR(100) NOT NULL,
)

CREATE TABLE NOMINA(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
AÑO VARCHAR(4) NOT NULL,
MES VARCHAR(9) NOT NULL,
MONTO_TOTAL VARCHAR (12) NOT NULL
)


CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY PRIMARY KEY,
NOMBRES VARCHAR (25) NOT NULL,
APELLIDOS VARCHAR(30) NOT NULL,
CEDULA VARCHAR(30) NOT NULL,
GENERO VARCHAR(30) NOT NULL,
TELEFONO VARCHAR(30) NOT NULL,
SUCURSAL INT FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL (ID_SUCURSAL),
CORREO NVARCHAR(255) NOT NULL,
USUARIO VARCHAR (25) NOT NULL,
CLAVE VARCHAR (30) NOT NULL
)

select * from CLIENTES


SELECT USUARIO,CLAVE FROM CLIENTES  WHERE USUARIO='"+acc.USUARIO+"' AND CLAVE='"+acc.CLAVE+"'

select * from CLIENTES WHERE USUARIO='MARCO'


CREATE TABLE SUCURSAL(
ID_SUCURSAL INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
TELEFONO VARCHAR(12) NOT NULL,
CORREO NVARCHAR(255) NOT NULL,
HORARIO VARCHAR (50) NOT NULL
)

USE COURRIER

DROP TABLE RECEPCION

CREATE TABLE RECEPCION(
ID_PRODUCTO INT IDENTITY PRIMARY KEY,
CLIENTE INT FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
PRODUCTO VARCHAR(80) NOT NULL,
ESTADO VARCHAR(10)NOT NULL,
FECHA_REGISTRO VARCHAR(20)NOT NULL,
ORIGEN VARCHAR(30)NOT NULL,
DESTINO INT FOREIGN KEY (DESTINO) REFERENCES SUCURSAL (ID_SUCURSAL),
PESO VARCHAR(10)NOT NULL,
PRECIO VARCHAR(10)NOT NULL,
)
select * from RECEPCION


